version: "3.8"

services:

  master:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: master
    restart: always
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./apps:/opt/bitnami/spark/apps
    ports:
      - "8081:8080"
      - "7077:7077"

  worker-1:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: worker-1
    restart: always
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=512M
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  worker-2:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: worker-2
    restart: always
    depends_on:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=512M
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  postgres:
    image: 'postgres:14.1-alpine'
    restart: 'always'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - './0.sql:/docker-entrypoint-initdb.d/0.sql'
    ports:
      - '5432:5432'

volumes:
  postgresdata:
