version: "3.8"

services:

  spark-master:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: spark-master
    restart: always
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark-app:/opt/spark-app

  spark-worker-1:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: spark-worker-1
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-app:/opt/spark-app

  spark-worker-2:
    image: bitnami/spark:3.5.1-debian-12-r6
    platform: linux/arm64
    container_name: spark-worker-2
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-app:/opt/spark-app

  postgres:
    image: 'postgres:14.1-alpine'
    restart: 'always'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - './0.sql:/docker-entrypoint-initdb.d/0.sql'
    ports:
      - '5432:5432'

volumes:
  postgresdata:
